import { StageType, PowerType, IStageConfig } from './types';

export const STAGE_CONFIGS: IStageConfig[] = [
  {
    type: StageType.MAIN,
    name: 'Etapa Principal',
    description: 'El desafío estándar. Recoge poderes en el camino.',
    emoji: '🌀',
    forcedPower: null,
    infinitePower: false,
    bgColor: 0x0a0a1a,
    accentColor: 0x6600ff,
    difficulty: 1.0,
    sceneKey: 'MainGameScene',
  },
  {
    type: StageType.POWER_SPEED,
    name: 'Etapa Velocidad',
    description: 'Domina la propulsión COHETE. Velocidad al máximo todo el tiempo.',
    emoji: '🚀',
    forcedPower: PowerType.SPEED_BOOST,
    infinitePower: true,
    bgColor: 0x1a0a00,
    accentColor: 0xff6600,
    difficulty: 1.0,
    sceneKey: 'PowerStageScene',
  },
  {
    type: StageType.POWER_SHIELD,
    name: 'Etapa Escudo',
    description: 'Protección total. Aprende a usar el escudo para sobrevivir.',
    emoji: '🛡️',
    forcedPower: PowerType.SHIELD,
    infinitePower: true,
    bgColor: 0x001a0a,
    accentColor: 0x00ff88,
    difficulty: 1.0,
    sceneKey: 'PowerStageScene',
  },
  {
    type: StageType.POWER_SCORE,
    name: 'Etapa Puntos',
    description: 'Multiplicador de puntuación activo. ¡Maximiza tu score!',
    emoji: '⭐',
    forcedPower: PowerType.SCORE_X2,
    infinitePower: true,
    bgColor: 0x1a1a00,
    accentColor: 0xffff00,
    difficulty: 1.0,
    sceneKey: 'PowerStageScene',
  },
  {
    type: StageType.POWER_GHOST,
    name: 'Etapa Fantasma',
    description: 'Atraviesa obstáculos. Descubre los límites del modo fantasma.',
    emoji: '👻',
    forcedPower: PowerType.GHOST,
    infinitePower: true,
    bgColor: 0x0a001a,
    accentColor: 0xcc00ff,
    difficulty: 1.0,
    sceneKey: 'PowerStageScene',
  },
  {
    type: StageType.POWER_FREEZE,
    name: 'Etapa Hielo',
    description: 'Todo congelado. Navega entre enemigos paralizados.',
    emoji: '❄️',
    forcedPower: PowerType.FREEZE,
    infinitePower: true,
    bgColor: 0x001a1a,
    accentColor: 0x00ffff,
    difficulty: 1.0,
    sceneKey: 'PowerStageScene',
  },
  {
    type: StageType.POWER_MAGNET,
    name: 'Etapa Imán',
    description: 'Atracción magnética activa. Aprende a controlar la atracción.',
    emoji: '🧲',
    forcedPower: PowerType.MAGNET,
    infinitePower: true,
    bgColor: 0x00001a,
    accentColor: 0x0088ff,
    difficulty: 1.0,
    sceneKey: 'PowerStageScene',
  },
  {
    type: StageType.POWER_SLOW,
    name: 'Etapa Cámara Lenta',
    description: 'El tiempo se ralentiza. Precisión sobre velocidad.',
    emoji: '🐌',
    forcedPower: PowerType.SLOW_EXTEND,
    infinitePower: true,
    bgColor: 0x1a000a,
    accentColor: 0xff0088,
    difficulty: 1.0,
    sceneKey: 'PowerStageScene',
  },
  {
    type: StageType.FINAL,
    name: 'Etapa Final',
    description: 'El desafío definitivo. Dificultad máxima. ¿Puedes llegar?',
    emoji: '🏆',
    forcedPower: null,
    infinitePower: false,
    bgColor: 0x0d0005,
    accentColor: 0xffd700,
    difficulty: 1.5,
    sceneKey: 'FinalStageScene',
  },
];

export function getStageConfig(type: StageType): IStageConfig {
  const config = STAGE_CONFIGS.find(s => s.type === type);
  if (!config) throw new Error(`StageConfig not found for type: ${type}`);
  return config;
}
